### ISSUE TITLE
Hello from Satya

### ISSUE THREAD

**Issue by satyadhuls** [pavankjadda/HashiCorpVault-SpringCloud#1]
Hi Pavan,
My name is Satya, this message is nothing about your code but wanted to reach out to you somehow but unsure how to send a private message on Github. I am having an issue related to Hashicorp.  We are using Hashicorp Vault in our project and am unable to figure out where the problem is connecting to the vault. I need your expertise if it is possible, searching online I came to your GitHub page and I am a newbie to Hashicorp.

Here is our situation:
1. We are using "Approle" authentication in our bootstrap.yml. 
2. How do you know where to lookup for our "app-role-path"?
3. What files should be there in our src/main/resources? I only have bootstrap.yml in my resources
4. Let's say my api url is: http://myapplication/xy/uef/vi/v2, should I be appending "/auth/approle/login" to my url so that it looks:
"http://myapplication/xy/uef/vi/v2/auth/approle/login"
5. What dependencies should I be using?
6. I am getting error 404 not found
7. Here is my bootstrap.yml
spring: 
  cloud:
    vault:
      authentication: APPROLE
      app-role:
        role-id: 783234-ab123-asdf45-45t454
        secret-id: 45863845-234365546-3454543-34534
        app-role-path: 2342323/nonprod/xyz (not sure where to lookup this value)
      uri: https://myapplication/xy/uef/vi/v2/auth/approle/login
      generic:
        enabled: true

My email address is: satyadhuls@gmail.com
Kindly please help me if possible, I am trying my best to find a solution but no avail online.

Thanks,
Satya.

**Comment by pavankjadda** [comment]
Please create an issue in StackOverflow as this is not forum to discuss issues like this. You can also my medium article on this

https://medium.com/@pavankjadda/hashicorpvault-with-springcloud-and-spring-boot-fada794216c3

**Comment by pavankjadda** [comment]
Ir upload code Github and paste link here
