### ISSUE TITLE
newest versions

### ISSUE THREAD

**Issue by maciejbak85** [pavankjadda/HashiCorpVault-SpringCloud#2]
hi,

did you try maybe upgrade spring-boot-starter-parent to 2.6.4, and spring cloud to 2021.0.1 ?
I am trying to make it working with those newest versions.
It works fine with those from your branch, but when I try to upgrade, I get nulls.

I have no idea how to fix that.
Maybe you know ?

thanks!

**Comment by pavankjadda** [comment]
@maciejbak85 try latest version `3.0.0` of the code. It should address all the issues. And also updated instructions

**Comment by maciejbak85** [comment]
thanks, but hmm still nulls, hmm

**Comment by pavankjadda** [comment]
> thanks, but hmm still nulls, hmm 

Did you follow instructions exactly as documented?

**Comment by pavankjadda** [comment]
Then it could be something else. If you can share a Github repo, I can take a look or create an issue in statck overflow. But closing the issue since it works for me with latest versions.
